In [2]:
import pandas as pd
import psycopg2
from psycopg2.extras import execute_values

In [3]:
df1 = pd.read_csv("clase_1.csv",sep=';')
df2 = pd.read_csv("clase_2.csv",sep=';')
df3 = pd.read_csv("clase_3.csv",sep=';')
df4 = pd.read_csv("clase_4.csv",sep=';')

In [4]:
df1.head()

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_HLF,Proyecto_EDA,Proyecto_BBDD,Proyecto_ML,Proyecto_Deployment
0,Jafet Casals,Jafet_Casals@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
1,Jorge Manzanares,Jorge_Manzanares@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
2,Onofre Adadia,Onofre_Adadia@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,No Apto,Apto
3,Merche Prada,Merche_Prada@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,No Apto,Apto,No Apto
4,Pilar Abella,Pilar_Abella@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto

In [5]:
df1.columns = df1.columns.str.strip()  # Elimina espacios en los nombres
df1.columns = df1.columns.str.replace(" ", "_")  # Sustituye espacios por guiones bajos
df2.columns = df2.columns.str.strip()  # Elimina espacios en los nombres
df2.columns = df2.columns.str.replace(" ", "_")  # Sustituye espacios por guiones bajos
df3.columns = df3.columns.str.strip()  # Elimina espacios en los nombres
df3.columns = df3.columns.str.replace(" ", "_")  # Sustituye espacios por guiones bajos
df4.columns = df4.columns.str.strip()  # Elimina espacios en los nombres
df4.columns = df4.columns.str.replace(" ", "_")  # Sustituye espacios por guiones bajos

In [9]:
dfalumnos1 = df1[["Nombre", "Email", "Fecha_comienzo"]]
dfalumnos2 = df2[["Nombre", "Email", "Fecha_comienzo"]]
dfalumnos3 = df3[["Nombre", "Email", "Fecha_comienzo"]]
dfalumnos4 = df4[["Nombre", "Email", "Fecha_comienzo"]]

dfpromocion1 = df1[["Promoción"]]
dfpromocion2 = df2[["Promoción"]]
dfpromocion3 = df3[["Promoción"]]
dfpromocion4 = df4[["Promoción"]]

dfalumnos1["Fecha_comienzo"] = pd.to_datetime(dfalumnos1["Fecha_comienzo"], format="%d/%m/%Y").dt.strftime("%Y-%m-%d")
dfalumnos2["Fecha_comienzo"] = pd.to_datetime(dfalumnos2["Fecha_comienzo"], format="%d/%m/%Y").dt.strftime("%Y-%m-%d")
dfalumnos3["Fecha_comienzo"] = pd.to_datetime(dfalumnos3["Fecha_comienzo"], format="%d/%m/%Y").dt.strftime("%Y-%m-%d")
dfalumnos4["Fecha_comienzo"] = pd.to_datetime(dfalumnos4["Fecha_comienzo"], format="%d/%m/%Y").dt.strftime("%Y-%m-%d")

dfalumnos = pd.concat([dfalumnos1,dfalumnos2,dfalumnos3,dfalumnos4], ignore_index= True)
dfpromocion = pd.concat([dfpromocion1,dfpromocion2,dfpromocion3,dfpromocion4], ignore_index= True)

C:\Users\34666\AppData\Local\Temp\ipykernel_9148\367232279.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfalumnos1["Fecha_comienzo"] = pd.to_datetime(dfalumnos1["Fecha_comienzo"], format="%d/%m/%Y").dt.strftime("%Y-%m-%d")
C:\Users\34666\AppData\Local\Temp\ipykernel_9148\367232279.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfalumnos2["Fecha_comienzo"] = pd.to_datetime(dfalumnos2["Fecha_comienzo"], format="%d/%m/%Y").dt.strftime("%Y-%m-%d")
C:\Users\34666\AppData\Local\Temp\ipykernel_9148\367232279.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfalumnos3["Fecha_comienzo"] = pd.to_datetime(dfalumnos3["Fecha_comienzo"], format="%d/%m/%Y").dt.strftime("%Y-%m-%d")
C:\Users\34666\AppData\Local\Temp\ipykernel_9148\367232279.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfalumnos4["Fecha_comienzo"] = pd.to_datetime(dfalumnos4["Fecha_comienzo"], format="%d/%m/%Y").dt.strftime("%Y-%m-%d")

In [7]:
dfalumnos

                  Nombre                           Email Fecha_comienzo
0           Jafet Casals          Jafet_Casals@gmail.com     2023-09-18
1       Jorge Manzanares      Jorge_Manzanares@gmail.com     2023-09-18
2          Onofre Adadia         Onofre_Adadia@gmail.com     2023-09-18
3           Merche Prada          Merche_Prada@gmail.com     2023-09-18
4           Pilar Abella          Pilar_Abella@gmail.com     2023-09-18
5           Leoncio Tena          Leoncio_Tena@gmail.com     2023-09-18
6        Odalys Torrijos       Odalys_Torrijos@gmail.com     2023-09-18
7       Eduardo Caparrós      Eduardo_Caparrós@gmail.com     2023-09-18
8     Ignacio Goicoechea    Ignacio_Goicoechea@gmail.com     2023-09-18
9      Clementina Santos     Clementina_Santos@gmail.com     2023-09-18
10         Daniela Falcó         Daniela_Falcó@gmail.com     2023-09-18
11         Abraham Vélez         Abraham_Vélez@gmail.com     2023-09-18
12  Maximiliano Menéndez  Maximiliano_Menéndez@gmail.com     2023-09-18
13         Anita Heredia         Anita_Heredia@gmail.com     2023-09-18
14             Eli Casas             Eli_Casas@gmail.com     2023-09-18
15     Guillermo Borrego     Guillermo_Borrego@gmail.com     2024-02-12
16        Sergio Aguirre        Sergio_Aguirre@gmail.com     2024-02-12
17       Carlito Carrión       Carlito_Carrión@gmail.com     2024-02-12
18       Haydée Figueroa       Haydée_Figueroa@gmail.com     2024-02-12
19         Chita Mancebo         Chita_Mancebo@gmail.com     2024-02-12
20      Joaquina Asensio      Joaquina_Asensio@gmail.com     2024-02-12
21      Cristian Sarabia      Cristian_Sarabia@gmail.com     2024-02-12
22         Isabel Ibáñez         Isabel_Ibáñez@gmail.com     2024-02-12
23       Desiderio Jordá       Desiderio_Jordá@gmail.com     2024-02-12
24       Rosalina Llanos       Rosalina_Llanos@gmail.com     2024-02-12
25        Amor Larrañaga        Amor_Larrañaga@gmail.com     2023-09-18
26      Teodoro Alberola      Teodoro_Alberola@gmail.com     2023-09-18
27           Cleto Plana           Cleto_Plana@gmail.com     2023-09-18
28      Aitana Sebastián      Aitana_Sebastián@gmail.com     2023-09-18
29      Dolores Valbuena      Dolores_Valbuena@gmail.com     2023-09-18
30          Julie Ferrer          Julie_Ferrer@gmail.com     2023-09-18
31        Mireia Cabañas        Mireia_Cabañas@gmail.com     2023-09-18
32         Flavia Amador         Flavia_Amador@gmail.com     2023-09-18
33         Albino Macias         Albino_Macias@gmail.com     2023-09-18
34         Ester Sánchez         Ester_Sánchez@gmail.com     2023-09-18
35    Luis Miguel Galvez    Luis_Miguel_Galvez@gmail.com     2023-09-18
36        Loida Arellano        Loida_Arellano@gmail.com     2023-09-18
37        Heraclio Duque        Heraclio_Duque@gmail.com     2023-09-18
38     Herberto Figueras     Herberto_Figueras@gmail.com     2023-09-18
39         Teresa Laguna         Teresa_Laguna@gmail.com     2024-02-12
40      Estrella Murillo      Estrella_Murillo@gmail.com     2024-02-12
41       Ernesto Uriarte       Ernesto_Uriarte@gmail.com     2024-02-12
42       Daniela Guitart       Daniela_Guitart@gmail.com     2024-02-12
43        Timoteo Trillo        Timoteo_Trillo@gmail.com     2024-02-12
44         Ricarda Tovar         Ricarda_Tovar@gmail.com     2024-02-12
45   Alejandra Vilaplana   Alejandra_Vilaplana@gmail.com     2024-02-12
46       Daniel Rosselló       Daniel_Rosselló@gmail.com     2024-02-12
47         Rita Olivares         Rita_Olivares@gmail.com     2024-02-12
48          Cleto Montes          Cleto_Montes@gmail.com     2024-02-12
49       Marino Castilla       Marino_Castilla@gmail.com     2024-02-12
50   Estefanía Valcárcel   Estefanía_Valcárcel@gmail.com     2024-02-12
51        Noemí Vilanova        Noemí_Vilanova@gmail.com     2024-02-12

In [10]:
dfpromocion

     Promoción
0   Septiembre
1   Septiembre
2   Septiembre
3   Septiembre
4   Septiembre
5   Septiembre
6   Septiembre
7   Septiembre
8   Septiembre
9   Septiembre
10  Septiembre
11  Septiembre
12  Septiembre
13  Septiembre
14  Septiembre
15     Febrero
16     Febrero
17     Febrero
18     Febrero
19     Febrero
20     Febrero
21     Febrero
22     Febrero
23     Febrero
24     Febrero
25  Septiembre
26  Septiembre
27  Septiembre
28  Septiembre
29  Septiembre
30  Septiembre
31  Septiembre
32  Septiembre
33  Septiembre
34  Septiembre
35  Septiembre
36  Septiembre
37  Septiembre
38  Septiembre
39     Febrero
40     Febrero
41     Febrero
42     Febrero
43     Febrero
44     Febrero
45     Febrero
46     Febrero
47     Febrero
48     Febrero
49     Febrero
50     Febrero
51     Febrero

In [ ]:



# Conectar a la base de datos
conn = psycopg2.connect(
    dbname="prueba_vitoria_tj76",
    user="prueba_vitoria_tj76_user",
    password="MiYx9YTBT7QvjEla235DuEfTBP8QxNpf",
    host="dpg-d10ni263jp1c73967r9g-a.frankfurt-postgres.render.com",
    port="5432"
)
cursor = conn.cursor()


# Insertar datos en la tabla 'Alumno' usando execute_values para mayor eficiencia
query = "INSERT INTO Alumnos ( Nombre, Email, Fecha_Comienzo) VALUES %s"
execute_values(cursor, query, dfalumnos.values.tolist())

#Inserta en promocion 

query = "INSERT INTO promocion ( nombre_promocion) VALUES %s"
execute_values(cursor, query, dfpromocion.values.tolist())


# Confirmar cambios y cerrar conexión
conn.commit()
cursor.close()
conn.close()